<!-- Distribuidor -->
<section class="container-fluid bg-gris text-azul text-center p-4 mb-5">

	<div class="row">
		<div class="distribuidor col-md-8 offset-md-2 d-flex flex-column justify-content-center">
			<div>
				<h3 class="mb-3 wow fadeInUp">¿QUERÉS SER DISTRIBUIDOR <br> DE LOS PRODUCTOS MOLDURAMA?</h3>
				<a href="contacto.php" class="btn btn_site font_1em wow fadeInUp">CONSULTAR</a>
			</div>
		</div>
  </div>

</section>
<!-- Distribuidor end -->