<!-- Footer -->
<footer class="container-fluid bg-negro text-white text-center p-4 mb-5">
	<div class="container">
		<div class="row">

			<div class="footer_logo col-md-6 mb-3">
				<img src="img/footer/moldurama-logo-byn.png" alt="logo moldurama byn">
			</div>

			<ul class="col-md-6 d-flex justify-content-around align-items-center">
				<li><a class="transition text-white" href="./nosotros.php">Nosotros</a></li>
				<li><a class="transition text-white" href="./zocalo-mdf-zfl.php">Productos</a></li>
				<li><a class="transition text-white" href="./contacto.php">Contacto</a></li>
			</ul>

	  </div>

	  <div class="dropdown-divider mb-4"></div>

	  <div class="row mb-3">

	  	<div class="col-md-4">
	  		<a class="transition text-white" href="tel:1147675100">
		  		<span><i class="transition fas fa-phone mb-3"></i>11.4767.5100</span>
		  	</a>			  		
	  	</div>

	  	<div class="col-md-4">
	  		<a class="transition text-white" href="mailto:info@moldurama.com.ar">
		  		<span><i class="transition fas fa-envelope mb-3"></i>info@moldurama.com.ar</span>
		  	</a>			  		
	  	</div>

	  	<div class="col-md-4">
	  		<a class="transition text-white" href="https://goo.gl/maps/toKmrUcCNkKDDKV2A" target="blank">
		  		<span><i class="transition fas fa-map-marker-alt mb-3"></i>La Paz 4546 - Villa Ballester</span>
		  	</a>			  		
	  	</div>

		</div>

		<div class="row">
		  <div class="col-md-8 offset-md-2 col-sm-12">
		  	<p>&copy; <?= date('Y'); ?>. MOLDURAMA todos los derechos reservados.</p>
			</div>
			<div class="col-md-2 text-right">
		  	<a class="transition libre" href="#">by Libre</a>
			</div>
		</div>

	</div>

</footer>
<!-- Footer end