<!-- Más Informacion -->
<section class="container-fluid bg-azul text-white text-center p-4 mb-5">

	<div class="row">
		<div class="distribuidor col-md-8 offset-md-2 d-flex flex-column justify-content-center">
			<div>
				<h3 class="mb-3 wow fadeInUp">Si necesitas más información sobre nuestros productos comunicate con nosotros</h3>
				<a href="contacto.php" class="btn btn_site_white font_1em wow fadeInLeft">CONSULTAR</a>
			</div>
		</div>
  </div>

</section>
<!-- Más Informacion end -->