<!-- Otros Productos -->
<section class="container-fluid bg-gris-claro mb-5 text-center">

	<div class="container">
		
	<div class="row mb-5">

		<div class="col-md-12 mb-3">
			<h3 class="otros_productos_h3">LÍNEA ZÓCALOS</h3>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-liso-zl22.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zl22.gif" alt="zocalo liso zl22">
				  <div class="card-body">
				    <h3 class="card-text">ZL22</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-liso-zl33.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zl33.gif" alt="zocalo liso ZL33">
				  <div class="card-body">
				    <h3 class="card-text">ZL33</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-moldurado-zm23.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zm23.gif" alt="zocalo moldurado ZM23">
				  <div class="card-body">
				    <h3 class="card-text">ZM23</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-moldurado-zm34.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zm34.gif" alt="zocalo moldurado ZM34">
				  <div class="card-body">
				    <h3 class="card-text">ZM34</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-mdf-zfl.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zfl.gif" alt="zocalo moldurado zfl">
				  <div class="card-body">
				    <h3 class="card-text">ZFL</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-mdf-zfr.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zfr.gif" alt="zocalo moldurado zfr">
				  <div class="card-body">
				    <h3 class="card-text">ZFR</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-mdf-zff.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zff.gif" alt="zocalo moldurado zff">
				  <div class="card-body">
				    <h3 class="card-text">ZFF</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="zocalo-mdf-zrc.php">
			  	<img class="card-img-top" src="img/productos/zocalo-zrc.gif" alt="zocalo moldurado zrc">
				  <div class="card-body">
				    <h3 class="card-text">ZRC</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="cubrezocalo-cz.php">
			  	<img class="card-img-top" src="img/productos/cubrezocalo-cz.gif" alt="cubrezocalo cz">
				  <div class="card-body">
				    <h3 class="card-text">CZ</h3>
				  </div>
			  </a>
			</div>
		</div>

		<div class="col-md-12 mb-3 mt-5">
			<h3 class="otros_productos_h3">LÍNEA CONTRAMARCOS</h3>
		</div>
		
		<div class="wow fadeInUp col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="contramarco-liso-cl22.php">
			  	<img class="card-img-top" src="img/productos/contramarco-cl22.gif" alt="contramarco cl22">
				  <div class="card-body">
				    <h3 class="card-text">CL22</h3>
				  </div>
			  </a>
			</div>
		</div>

		<!-- <div class="wow fadeInUp col-md-3 col-6 text-center mb-3">
			<div class="card">
				<a class="transition" href="contramarco-moldurado-cm23.php">
			  	<img class="card-img-top" src="img/productos/contramarco-cm23.gif" alt="contramarco cm23">
				  <div class="card-body">
				    <h3 class="card-text">CM23</h3>
				  </div>
			  </a>
			</div>
		</div> -->

	</div>

</div>
</section>
<!-- Otros Productos end -->