<!-- Otros Productos -->
<section class="container-fluid bg-gris-claro mb-5 text-center otros_productos">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-12 mb-3">
        <h3 class="otros_productos_h3">LÍNEA ZÓCALOS</h3>
      </div>

      <div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="zocalo-mdf-zfl.php">
            <img
              class="card-img-top"
              src="img/productos/zocalo-zfl.gif"
              alt="zocalo moldurado zfl"
            />
            <div class="card-body">
              <h3 class="card-text">ZFL</h3>
              <p>Zócalo Curvo</p>
            </div>
          </a>
        </div>
      </div>

      <div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="zocalo-mdf-zfr.php">
            <img
              class="card-img-top"
              src="img/productos/zocalo-zfr.gif"
              alt="zocalo moldurado zfr"
            />
            <div class="card-body">
              <h3 class="card-text">ZFR</h3>
              <p>Zócalo Recto</p>
            </div>
          </a>
        </div>
      </div>

      <div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="zocalo-mdf-zff.php">
            <img
              class="card-img-top"
              src="img/productos/zocalo-zff.gif"
              alt="zocalo moldurado zff"
            />
            <div class="card-body">
              <h3 class="card-text">ZFF</h3>
              <p>Zócalo Fantasía</p>
            </div>
          </a>
        </div>
      </div>

      <div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="zocalo-mdf-zfc.php">
            <img
              class="card-img-top"
              src="img/productos/zocalo-zfc.gif"
              alt="zocalo moldurado zfc"
            />
            <div class="card-body">
              <h3 class="card-text">ZFC</h3>
              <p>Zócalo con Calle</p>
            </div>
          </a>
        </div>
      </div>

      <div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="zocalo-mdf-zfm.php">
            <img
              class="card-img-top"
              src="img/productos/zocalo-zfm.gif"
              alt="zocalo moldurado zfm"
            />
            <div class="card-body">
              <h3 class="card-text">ZFM</h3>
              <p>Zócalo Moldurado</p>
            </div>
          </a>
        </div>
      </div>

      <div class="wow fadeInLeft col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="cubrezocalo-cz.php">
            <img
              class="card-img-top"
              src="img/productos/cubrezocalo-cz.gif"
              alt="cubrezocalo cz"
            />
            <div class="card-body">
              <h3 class="card-text">CZ</h3>
              <p>Cubrezócalo</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-md-12 mb-3 mt-5">
        <h3 class="otros_productos_h3">LÍNEA CONTRAMARCOS</h3>
      </div>

      <div class="wow fadeInUp col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="contramarco-recto-cfr.php">
            <img
              class="card-img-top"
              src="img/productos/contramarco-cfr.gif"
              alt="contramarco cfr"
            />
            <div class="card-body">
              <h3 class="card-text">CFR</h3>
              <p>Contramarco Recto</p>
            </div>
          </a>
        </div>
      </div>

      <div class="col-md-12 mb-3 mt-5">
        <h3 class="otros_productos_h3">LÍNEA GUARDASILLAS</h3>
      </div>

      <div class="wow fadeInUp col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="guardasilla-liso-gfm.php">
            <img
              class="card-img-top"
              src="img/productos/guardasillas-gfm.gif"
              alt="guardasillas gfm"
            />
            <div class="card-body">
              <h3 class="card-text">GFM</h3>
              <p>Guardasilla Moldurado</p>
            </div>
          </a>
        </div>
      </div>

      <div class="wow fadeInUp col-md-3 col-6 text-center mb-3">
        <div class="card">
          <a class="transition" href="guardasilla-recto-gfr.php">
            <img
              class="card-img-top"
              src="img/productos/guardasillas-gfr.gif"
              alt="guardasillas gfr"
            />
            <div class="card-body">
              <h3 class="card-text">GFR</h3>
              <p>Guardasilla Recto</p>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Otros Productos end -->
