<!-- Slider -->
<section class="container-fluid p-0 mb-5">

	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

	  <ol class="carousel-indicators">
	    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
	    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
	    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
	  </ol>

	  <div class="carousel-inner">

	  	<div class="carousel-item active">
			  <img class="img-fluid" src="img/slide/slide-a.jpg" alt="colores zocalos de mdf blanco">
			  <div class="carousel-caption carousel-caption_add carousel-caption_mdf">
			  	<div class="row">
			  		<div class="col-sm-9">
					    <h1>ZÓCALOS EN MDF</h1>
							<p>
								Zócalos de alta calidad listos para colocar.<br>Medidas y colores personalizables.
							</p>
							<a href="zocalo-mdf-zff.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>							
			  		</div>
			  	</div>
			  </div>
			</div>

	    <div class="carousel-item">
			  <img class="img-fluid" src="img/slide/slide-b.jpg" alt="colores zocalos de madera">
			  <div class="carousel-caption carousel-caption_add carousel-caption_menor">
			  	<div class="row">
			  		<div class="col-sm-9">
					    <h1>EXPLORÁ NUEVOS COLORES</h1>
							<p>
								Dale color a tus ambientes.
							</p>
							<a href="contacto.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>							
			  		</div>
			  	</div>
			  </div>
			</div>

			<div class="carousel-item ">
			  <img class="img-fluid" src="img/slide/slide-d.jpg" alt="contramarcos de madera">
			  <div class="carousel-caption carousel-caption_add">
			  	<div class="row">
			  		<div class="col-sm-8">
					    <h1>CONTRAMARCOS <br>EN MADERA</h1>
							<p>Descubrí nuestra línea de <br> contramarcos y embellece <br>tus ambientes.</p>
							<a href="contramarco-liso-cl22.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>
			  		</div>
			  	</div>
			  </div>
			</div>

			<div class="carousel-item">
			  <img class="img-fluid" src="img/slide/slide-c.jpg" alt="zocalos de madera">
			  <div class="carousel-caption carousel-caption_add">
			  	<div class="row">
			  		<div class="col-sm-7">
					    <h1>CUBREZÓCALOS EN MDF</h1>
							<p>Conocé nuestra línea de <br>cubrezócalos. Se colocan sobre los <br>existentes y se pueden ocultar cables en su interior.</p>
							<a href="zocalo-moldurado-zm23.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>
			  		</div>
			  	</div>
			  </div>
			</div>

	  </div>

	  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>

	  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>

	</div>

	<!-- Slider Mobile -->
	<div id="carousel_mobile" class="carousel slide" data-ride="carousel">
	  <div class="carousel-inner">

	    <div class="carousel-item active">
	      <img class="img-fluid" src="img/slide/slide-a.jpg" alt="zocalos de colores de madera en mdf blancos plenos">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">ZÓCALOS EN MDF</h5>
	        <p>Zócalos de alta calidad listos para colocar.</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-b.jpg" alt="zocalos de colores plenos">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">EXPLORÁ NUEVOS COLORES</h5>
	        <p>Dale color a tus ambientes.</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-d.jpg" alt="contramarcos de madera mobile">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">CONTRAMARCOS EN MADERA</h5>
	        <p>Descubrí nuestra línea de contramarcos.</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-c.jpg" alt="zocalos de madera mobile">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">ZÓCALOS EN MADERA</h5>
	        <p>La distinción final a tus ambientes.</p>
		    </div>
	    </div>

	  </div>

	  <a class="carousel-control-prev" href="#carousel_mobile" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carousel_mobile" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	<!-- Slider Mobile end -->

</section>
<!-- Slider end