<!-- Slide Home -->
<section class="container-fluid p-0 mb-5">

	<!-- Slide Desktop -->
	<div id="carousel_desktop" class="carousel slide" data-ride="carousel">

	  <ol class="carousel-indicators">
	    <li data-target="#carousel_desktop" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel_desktop" data-slide-to="1"></li>
	    <li data-target="#carousel_desktop" data-slide-to="2"></li>
	    <li data-target="#carousel_desktop" data-slide-to="3"></li>
	    <li data-target="#carousel_desktop" data-slide-to="4"></li>
	  </ol>

	  <div class="carousel-inner">

	  	<div class="carousel-item active">
			  <img class="img-fluid" src="img/slide/slide-a.jpg" alt="colores zocalos de mdf blanco">
			  <div class="carousel-caption carousel-caption_add carousel-caption_mdf">
			  	<div class="row">
			  		<div id="text_primer_slide" class="col-sm-9 col-md-10">
					    <h1>ZÓCALOS EN MDF</h1>
							<p>
								Zócalos de alta calidad listos para colocar. <br>Medidas y colores personalizados.
							</p>
							<a href="./zocalo-mdf-zff.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>
			  		</div>
			  	</div>
			  </div>
			</div>

	    <div class="carousel-item">
			  <img class="img-fluid" src="img/slide/slide-b.jpg" alt="colores zocalos de madera">
			  <div class="carousel-caption carousel-caption_add carousel-caption_menor">
			  	<div class="row">
			  		<div id="text_segundo_slide" class="col-sm-9 col-md-10">
					    <h2>EXPLORÁ NUEVOS COLORES</h2>
							<p>Personalizá tus ambientes.</p>
							<a href="contacto.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>							
			  		</div>
			  	</div>
			  </div>
			</div>

			<div class="carousel-item">
			  <img class="img-fluid" src="img/slide/slide-d.jpg" alt="contramarcos de madera">
			  <div class="carousel-caption carousel-caption_add">
			  	<div class="row">
			  		<div id="text_tercer_slide" class="col-sm-6">
					    <h2>CONTRAMARCOS EN MDF</h2>
							<p>Detalles que diferencian tus ambientes</p>
							<a href="contramarco-liso-cl22.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>
			  		</div>
			  	</div>
			  </div>
			</div>

			<div class="carousel-item">
			  <img class="img-fluid" src="img/slide/slide-c.jpg" alt="zocalos de madera">
			  <div class="carousel-caption carousel-caption_add">
			  	<div class="row">
			  		<div id="text_cuarto_slide" class="col-sm-8 col-md-9">
					    <h2>CUBREZÓCALOS EN MDF</h2>
							<p>Se colocan sobre los existentes <br>y se pueden ocultar cables en su interior.</p>
							<a href="zocalo-moldurado-zm23.php" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>
			  		</div>
			  	</div>
			  </div>
			</div>

			<div class="carousel-item">
			  <img class="img-fluid" src="img/slide/slide-e.jpg" alt="guarda silla en mdf">
			  <div class="carousel-caption carousel-caption_add">
			  	<div class="row">
			  		<div id="text_cuarto_slide" class="col-sm-8">
					    <h2>GUARDASILLAS EN MDF</h2>
							<p>Protección y estilo para tus ambientes.</p>
							<a href="#" class="transition btn btn-slide"><i class="transition fas fa-plus"></i>&nbsp;Info</a>
			  		</div>
			  	</div>
			  </div>
			</div>

	  </div>

	  <a class="carousel-control-prev" href="#carousel_desktop" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>

	  <a class="carousel-control-next" href="#carousel_desktop" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>

	</div>
	<!-- Slide Desktop end -->






	<!-- Slide Mobile -->
	<div id="carousel_mobile" class="carousel slide" data-ride="carousel">
	  <div class="carousel-inner">

	    <div class="carousel-item active">
	      <img class="img-fluid" src="img/slide/slide-a.jpg" alt="zocalos de colores de madera en mdf blancos plenos">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">ZÓCALOS EN MDF</h5>
	        <p>Zócalos de alta calidad listos para colocar.</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-b.jpg" alt="zocalos de colores plenos">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">EXPLORÁ NUEVOS COLORES</h5>
	        <p>Personalizá tus ambientes.</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-d.jpg" alt="contramarcos de madera mobile">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">CONTRAMARCOS EN MDF</h5>
	        <p>Detalles que diferencian tus ambientes</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-c.jpg" alt="zocalos de madera mobile">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">CUBREZÓCALOS EN MDF</h5>
	        <p>Se colocan sobre los zócalos existentes</p>
		    </div>
	    </div>

	    <div class="carousel-item">
	      <img class="img-fluid" src="img/slide/slide-e.jpg" alt="guarda silla en mdf mobile">
		    <div class="slide_caption_mobile">
		    	<h5 class="text-center">GUARDASILLAS EN MDF</h5>
	        <p>Protección y estilo para tus ambientes.</p>
		    </div>
	    </div>

	  </div>

	  <a class="carousel-control-prev" href="#carousel_mobile" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carousel_mobile" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	<!-- Slide Mobile -->

</section>
<!-- Slide Home end