<div class="container-fluid carrusel_home wow fadeInUp">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div
          id="carouselProductsControls"
          class="carousel slide"
          data-ride="carousel"
        >
          <div class="carousel-inner">
            <!-- Wall Panel acanalado en MDF -->
            <div class="carousel-item active">
              <section class="mdf_blancos wall_panel">
                <div class="row">
                  <div class="content_img col-md-6">
                    <a class="link_to_product transition" href="./wall-panel-acanalado.php">
                      <img
                        class="img-fluid"
                        src="img/home/wall-panel-acanalado.jpg"
                        alt="Wall Panel acanalado en MDF"
                      />
                    </a>
                  </div>

                  <div class="info col-md-6">
                    <a class="link_to_product transition" href="./wall-panel-acanalado.php">
                      <span class="nuevo_desktop text-right">NUEVO</span>
                      <h4>WALL PANEL<br />ACANALADO MDF</h4>
                      <span class="listos_colocar">LISTOS PARA COLOCAR</span>
                      <p>
                        <strong>MEDIDAS:</strong><br />Cada tira mide 135 mm de
                        ancho x 2750mm de alto<br />
                        <strong>ESPESOR:</strong><br />9mm <br />
                        <strong>PRESENTACIÓN:</strong><br />Cada empaque contiene
                        10 tiras de revestimiento que cubren 3,50 m2. <br />
                        <strong>COLORES:</strong><br />Prepintado y Natural.
                      </p>
                      <div class="wow fadeInUp content_colors">
                        <div class="colors bg-blank">&nbsp;</div>
                        <div class="colors bg-natural">&nbsp;</div>
                      </div>
                    </a>
                  </div>
                </div>
              </section>
            </div>
            <!-- Wall Panel acanalado en MDF end -->

            <!-- Wall Panel ranurado en MDF -->
            <div class="carousel-item">
              <section class="mdf_blancos wall_panel">
                <div class="row">
                  <div class="content_img col-md-6">
                    <a class="link_to_product transition" href="./wall-panel-ranurados.php">
                      <img
                        class="img-fluid"
                        src="img/home/wall-panel-ranurado.jpg"
                        alt="Wall Panel ranurado en MDF"
                      />
                    </a>
                  </div>

                  <div class="info col-md-6">
                    <a class="link_to_product transition" href="./wall-panel-ranurados.php">
                      <span class="nuevo_desktop text-right">NUEVO</span>
                      <h4>WALL PANEL<br />RANURADO MDF</h4>
                      <span class="listos_colocar">LISTOS PARA COLOCAR</span>
                      <p>
                        <strong>MEDIDAS:</strong><br />Cada tira mide 135 mm de
                        ancho x 2750mm de alto<br />
                        <strong>ESPESOR:</strong><br />9mm <br />
                        <strong>PRESENTACIÓN:</strong><br />Cada empaque contiene
                        10 tiras de revestimiento que cubren 3,50 m2. <br />
                        <strong>COLORES:</strong><br />Prepintado y Natural.
                      </p>
                      <div class="wow fadeInUp content_colors">
                        <div class="colors bg-blank">&nbsp;</div>
                        <div class="colors bg-natural">&nbsp;</div>
                      </div>
                    </a>
                  </div>
                </div>
              </section>
            </div>
            <!-- Wall Panel ranurado en MDF end -->

            <!-- Respaldos de Cama en MDF -->
            <div class="carousel-item">
              <section class="mdf_blancos wall_panel">
                <div class="row">
                  <div class="content_img col-md-6">
                    <a class="link_to_product transition" href="./respaldos-cama-1-plaza.php">
                      <img
                        class="img-fluid"
                        src="img/home/respaldos-cama.jpg"
                        alt="Respaldos de Cama en MDF"
                      />
                    </a>
                  </div>

                  <div class="info col-md-6">
                    <a class="link_to_product transition" href="./respaldos-cama-1-plaza.php">
                      <span class="nuevo_desktop text-right">NUEVO</span>
                      <h4>RESPALDOS DE CAMA MDF<br />1 PLAZA, 2 PLAZAS Y KING</h4>
                      <span class="listos_colocar">LISTOS PARA COLOCAR</span>
                      <p>
                        <strong>DESCRIPCIÓN:</strong><br />Fabricados en MDF con
                        dos colgadores para el montaje, lo que permite ajustar la
                        altura según preferencia. <br />
                        <strong>MEDIDAS:</strong><br />Con un alto estándar de 91
                        cm y un espesor de 3 cm. Disponible en 3 medidas de ancho:
                        99 cm para camas de 1 plaza, 169 cm para camas de 2 plazas
                        y 210 cm para camas King.<br />
                        <strong>COLORES:</strong><br />Prepintado y Natural.
                      </p>
                      <div class="wow fadeInUp content_colors">
                        <div class="colors bg-blank">&nbsp;</div>
                        <div class="colors bg-natural">&nbsp;</div>
                      </div>
                    </a>
                  </div>
                </div>
              </section>
            </div>
            <!-- Respaldos de Cama en MDF end -->

            <!-- Zocalos MDF Blanco -->
            <div class="carousel-item">
              <section class="mdf_blancos wall_panel">
                <div class="row">
                  <div class="content_img col-md-6">
                    <a class="link_to_product transition" href="./zocalo-mdf-zff.php">
                      <img
                        class="img-fluid"
                        src="img/home/zocalo-mdf-blanco.jpg"
                        alt="zocalos en mdf blancos"
                      />
                    </a>
                  </div>

                  <div class="info col-md-6">
                    <a class="link_to_product transition" href="./zocalo-mdf-zff.php">
                      <h4>ZÓCALOS EN MDF<br />BLANCO PREMIUM</h4>
                      <span class="listos_colocar">LISTOS PARA COLOCAR</span>
                      <p>
                        <strong>ALTURA:</strong><br />50 mm, 70 mm, 82 mm, 100 mm
                        y 120 mm<br />
                        <strong>ESPESOR:</strong><br />12 mm<br />
                        <strong>COLORES:</strong><br />Blanco, gris, negro y
                        personalizados a pedido<br />
                      </p>
                      <div class="wow fadeInUp content_colors">
                        <div class="colors bg-blank">&nbsp;</div>
                        <div class="colors bg-gris">&nbsp;</div>
                        <div class="colors bg-negro">&nbsp;</div>
                      </div>
                    </a>
                  </div>
                </div>
              </section>
            </div>
            <!-- Zocalos MDF Blanco end -->
          </div>

          <button
            class="carousel-control-prev"
            type="button"
            data-target="#carouselProductsControls"
            data-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </button>

          <button
            class="carousel-control-next"
            type="button"
            data-target="#carouselProductsControls"
            data-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
