<!-- Seccion Seguidor -->
<section id="seguidor" class="text-center animated fadeInRight">
  <button id="cerrar-seguidor" style="color: #000000">
    <i style="font-size: 1.25em; float: right" class="fas fa-times-circle"></i>
  </button>

  <hr style="margin: 10px 0" />

  <div class="click-to-call-mobile">
    <i class="fab fa-whatsapp"></i>
  </div>

  <h6><strong>¡CONSULTÁ POR WHATSAPP!</strong></h6>

  <a
    id="desktop_site_whatsapp"
    class="btn btn-yellow"
    target="_blank"
    href="https://web.whatsapp.com/send?phone=+5491135968714&text=Hola!%20Necesito%20hacer%20una%20consulta!"
  >
    CHAT
  </a>
</section>

<section id="seguidor-tel" class="text-center">
  <div class="tex-right">
    <button id="cerrar-seguidor-tel" style="color: #000000">
      <i style="font-size: 1.25em" class="fas fa-times-circle"></i>
    </button>
  </div>
  <a
    id="mobile_site_whatsapp"
    class="transition"
    target="_blank"
    href="https://api.whatsapp.com/send?phone=5491135968714&text=Hola!%20Necesito%20hacer%20una%20consulta!"
  >
    <h5>
      ¡CONSULTÁ POR <br />
      WHATSAPP!
    </h5>
  </a>
</section>
<!-- Fin Seccion Seguidor -->
